
default: &default
  adapter: postgresql
  encoding: unicode
  user: Wander
  password: wander
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: library_development
